#Table Booking and Online Delivery
import pandas as pd
df=pd.read_csv("Dataset .csv")
#1. Determine the percentage of restaurants that offer table booking and online delivery
print("Table Booking: ")
print("")
Table_Booking=df["Has Table booking"].value_counts(normalize=True)*100
print(Table_Booking)
yes_tb=Table_Booking.get("Yes",0)
no_tb=Table_Booking.get("No",0)
print(f"{yes_tb:.2f} % of restaurants have table booking")
print(f"{no_tb:.2f} % of restaurants does not have table booking")
print("")
print("Online Delivery: ")
print("")
Online_Delivery=df["Has Online delivery"].value_counts(normalize=True)*100
print(Online_Delivery)
yes_od=Online_Delivery.get("Yes",0)
no_od=Online_Delivery.get("No",0)
print(f"{yes_od:.2f} % of restaurants, have online delivery")
print(f"{no_od:.2f} % of restaurants, does not have online delivery")
#2. Compare the average ratings of restaurants with table booking and without
print("")
print("Average rating of the restaurants with table booking and without : ")
print("")
Average_Rating_Restaurant=df.groupby("Has Table booking")["Aggregate rating"].mean()
print(Average_Rating_Restaurant)
avg_yes=Average_Rating_Restaurant.get("Yes",0)
avg_no=Average_Rating_Restaurant.get("No",0)
print(f"{avg_yes:.2f} is the average rating of restaurant with table booking")
print(f"{avg_no:.2f} is the average rating of restaurants without table booking")
#3. Availability of online delivery among restaurants with different price ranges
print("")
print("Availabilty of online delivery across different restaurants with different price ranges: ")
print("")
delivery_price_range=pd.crosstab(df["Price range"],df["Has Online delivery"],normalize='index')*100
print(delivery_price_range)
with open("Task_4_text_output.txt","w") as f:
    f.write("Table Booking and Online Delivery\n\n")
    f.write("Determine the percentage of restaurants that offer table booking and online delivery: \n\n")
    f.write("Table Booking: \n")
    f.write(str(df["Has Table booking"].value_counts(normalize=True)*100))
    f.write("\n")
    f.write(f"{yes_tb:.2f} % of the restaurants offer table booking while {no_tb:.2f} % of the restaurants does not offer table booking\n")
    f.write("Online Delivery: \n")
    f.write(str(df["Has Online delivery"].value_counts(normalize=True)*100))
    f.write("\n")
    f.write(f"{yes_od:.2f} % of the restaurants offer online delivery while {no_od:.2f} % of the restaurants does not offer online delivery\n")
    f.write("Comparing the average rating of the restaurants with table booking and without table booking: \n\n")
    f.write(str(df.groupby("Has Table booking")["Aggregate rating"].mean()))
    f.write("\n")
    f.write(f"{avg_yes:.2f} is the average rating of the restaurants with table booking and {avg_no} is the average rating of the restaurants without table booking\n")
    f.write("The Availability of online delivery amoung restaurants with different price ranges\n\n")
    f.write(str(pd.crosstab(df["Price range"],df["Has Online delivery"],normalize='index')*100))
    f.write("\n")