import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("Dataset .csv")
df.head()
df=df[["Cuisines","Aggregate rating","Votes"]]
df=df.dropna(subset=["Cuisines"])
df=df.assign(Cuisines=df["Cuisines"].str.split(", "))
df=df.explode("Cuisines")
cuisine_rating=df.groupby("Cuisines")["Aggregate rating"].mean().sort_values(ascending=False)
print(cuisine_rating.head(10))
cuisine_votes=df.groupby("Cuisines")["Votes"].sum().sort_values(ascending=False)
print(cuisine_votes.head(10))
high_rating_cuisines= (df.groupby("Cuisines").agg(avg_rating=("Aggregate rating","mean"),total_votes=("Votes","sum")).query("total_votes>500").sort_values(by="avg_rating",ascending=False))
print(high_rating_cuisines.head(10))
cuisine_rating.head(10).plot(kind="bar",figsize=(10,12))
plt.title("Top 10 Cuisines by Average Rating")
plt.xlabel("Cuisine")
plt.ylabel("Average Rating")
plt.savefig("Top 10 Cuisines by Average Rating.png",dpi=300,bbox_inches="tight")
plt.show()
with open("Task_8_output_text.txt","w",encoding="utf-8") as f:
    f.write("Customer Preference Analysis \n\n")
    f.write("Cuisines Rating: \n")
    f.write(str(cuisine_rating.head(10)))
    f.write("\n")
    f.write("Cuisines Votes: \n")
    f.write(str(cuisine_votes.head(10)))
    f.write("\n")
    f.write("The Higest rating cuisines: \n")
    f.write(str(high_rating_cuisines.head(10)))