import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("Dataset .csv")
plt.figure(figsize=(10,12))
plt.hist(df["Aggregate rating"],bins=10)
plt.xlabel("Aggregate Rating")
plt.ylabel("Number of Restaurants")
plt.title("Distribution of Restaurant Ratings")
plt.savefig("Distribution of Restaurant Ratings.png",dpi=300,bbox_inches="tight")
plt.show()
rating_counts=df["Aggregate rating"].value_counts().sort_index()
plt.figure(figsize=(10,12))
plt.bar(rating_counts.index,rating_counts.values)
plt.xlabel("Aggregate Rating")
plt.ylabel("Count")
plt.title("Count of Restaurants of Rating")
plt.savefig("Count of Restaurants of Rating.png",dpi=300,bbox_inches="tight")
plt.show()
top_cuisines=df["Cuisines"].value_counts().head(10).index
cuisine_avg=df[df["Cuisines"].isin(top_cuisines)].groupby("Cuisines")["Aggregate rating"].mean()
plt.figure(figsize=(10,12))
cuisine_avg.sort_values().plot(kind="bar")
plt.xlabel("Average Rating")
plt.ylabel("Cuisines")
plt.title("Average Rating by Top 10 Cuisines")
plt.savefig("Average Rating by Top 10 Cuisines.png",dpi=300,bbox_inches="tight")
plt.show()
plt.figure(figsize=(10,12))
plt.scatter(df["Average Cost for two"],df["Aggregate rating"])
plt.xlabel("Average Cost for two")
plt.ylabel("Aggregate Rating")
plt.title("Cost VS Aggregate Rating")
plt.savefig("Cost VS Aggregate Rating.png",dpi=300,bbox_inches="tight")
plt.show()
plt.figure(figsize=(10,12))
sns.boxplot(x="Price range", y="Aggregate rating", data=df)
plt.xlabel("Price Range")
plt.ylabel("Aggregate Rating")
plt.title("Price Range VS Aggregate Rating")
plt.savefig("Price Range VS Aggregate Rating.png",dpi=300,bbox_inches="tight")
plt.show()
plt.figure(figsize=(10,12))
sns.boxplot(x="Has Table booking", y="Aggregate rating",data=df)
plt.xlabel("Has Table Booking")
plt.ylabel("Aggregate Rating")
plt.title("Table Booking vs Aggregate Rating")
plt.savefig("Table Booking VS Aggregate Rating.png",dpi=300,bbox_inches="tight")
plt.show()
plt.figure(figsize=(10,12))
sns.boxplot(x="Has Online delivery", y="Aggregate rating",data=df)
plt.xlabel("Has Online Delivery")
plt.ylabel("Aggregate Rating")
plt.title("Online Delivery vs Aggrgate Rating")
plt.savefig("Online Delivery VS Aggregate Rating.png",dpi=300,bbox_inches="tight")
plt.show()
